apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  namespace: board
  labels:
    app: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: aramidhwan/board:latest
          ports:
            - containerPort: 8090
          env:
            - name: BOARD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: dev-secret
                  key: url
            - name: BOARD_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: dev-configmap
                  key: username
            - name: BOARD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-secret
                  key: password
